pipelines:
  gocd-rpi-unicorn-hat-monitor:
    group: defaultGroup
    locking: off
    materials:
      main_repo:
        git: https://github.com/manojphatak/trial.git
        branch: master
    stages:
      - test:
          clean_workspace: false
          jobs:
            unit:
              tasks:
               - exec:
                   command: python
                   arguments:
                    - sandbox.py
               
